apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-v2
  namespace: namespace-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
      version: v2
  template:
    metadata:
      labels:
        app: app-1
        version: v2
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - name: apache
          containerPort: 8080
        resources:
          limits:
            memory: 16Mi
            cpu: 60m
          requests:
            memory: 16Mi
            cpu: 40m
        volumeMounts:
        - name: config
          mountPath: /app/index.html
          subPath: index.html
      volumes:
      - name: config
        configMap:
          name: app-1-v2

